INSERT INTO ADMIN.GRAO (ID_GRAO, DESCRICAO) VALUES (0, 'N�o se aplica');
INSERT INTO ADMIN.GRAO (ID_GRAO, DESCRICAO) VALUES (3, 'Semente');
INSERT INTO ADMIN.GRAO (ID_GRAO, DESCRICAO) VALUES (8, 'Gr�o/Consumo');
