INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('505409017','1','Seberi');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512434468','1','Mato Queimado');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511529411','1','Vera Cruz do Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512386443','1','Estrela Velha');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509060742','1','Colorado');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512871403','1','Abdon Batista');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506629656','2','Saldanha Marinho');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510561620','1','Alpestre');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510337362','1','Porto Xavier');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512322821','1','Faxinalzinho');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510625519','1','Doutor Maurício Cardoso');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512742935','2','São Pedro do Butiá');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510777826','1','São Mateus do Sul');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511422757','1','Boa Esperança do Iguaçu');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510632161','1','Rondinha');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512544818','1','São José dos Pinhais');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512266304','1','Boa Vista do Buricá');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506892397','1','Alfredo Wagner');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506583307','1','Humaitá');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509770643','1','Sabáudia');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('514667475','1','Paulo Bento');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506677736','1','Estação');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509621226','1','Missal');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508261237','1','Pérola d'Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508895305','1','Jaboticaba');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512465784','1','União da Serra');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('514024136','1','Aurora');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512339396','1','Ibirapuitã');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511973297','1','Liberato Salzano');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512679824','1','Joaçaba');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511649391','1','Formosa do Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511642234','1','Santo Ângelo');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511912495','1','Dois Vizinhos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510353611','1','Boa Vista do Buricá');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510091047','1','São João');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513167436','1','Pinhal');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510163534','1','Bozano');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508189186','1','Sertão');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512469782','1','Trindade do Sul');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512233438','1','Tupanciretã');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506441232','1','Bela Vista da Caroba');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510735747','1','Centenário');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508816745','1','Santa Maria');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512418127','1','Dois Vizinhos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512344927','1','Rio Bonito do Iguaçu');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('507930286','1','Francisco Beltrão');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('505409017','2','Seberi');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512456619','1','Chapada');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511433060','1','Cândido de Abreu');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512616055','1','Rolador');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510150896','1','Vidal Ramos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513994955','1','Virmond');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508185125','1','Chapada');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512392519','2','Victor Graeff');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512428214','1','Celso Ramos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('504883459','1','Vista Alegre');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512291190','1','Atalanta');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511814125','1','Santa Izabel do Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513043208','1','Alpestre');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508896294','1','Vanini');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510119042','1','Capanema');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512701247','1','Espumoso');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508398980','1','Taquaritinga');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511860840','1','Missal');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510567603','1','Realeza');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511280419','1','Ampére');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513597311','1','Estrela Velha');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513802737','1','Barra Funda');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513829409','1','Céu Azul');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513162675','1','Capitão Leônidas Marques');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511177174','1','Terra Roxa');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('507060248','1','Jussara');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('504922375','1','São Miguel das Missões');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511409753','1','Alpestre');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('514390988','1','Vidal Ramos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512529549','1','Nova Alvorada');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508729063','1','Lagoa dos Três Cantos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508362156','1','Laranjal');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508920137','1','Estação');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511441784','1','Planalto');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513606060','1','Juranda');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('514219791','1','Três de Maio');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506742889','1','Ortigueira');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512763117','1','Sinimbu');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510083674','1','São João');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508759430','2','Ivaí');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508289678','1','Ivaiporã');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510020586','1','Antônio Prado');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513579445','2','Carira');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513203730','1','Verê');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509869911','1','Capanema');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513401648','1','Enéas Marques');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510674127','1','Boa Vista do Incra');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508460383','1','Fortaleza dos Valos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511635981','1','Céu Azul');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509189351','1','Caxias do Sul');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512496936','1','Três Passos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509590812','1','Três Barras do Paraná');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510484559','1','Cerro Grande');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513551202','1','Coronel Vivida');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510431667','2','Erval Velho');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('504883459','2','Frederico Westphalen');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509016164','1','Santiago');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512882756','1','Protásio Alves');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512261273','1','Verê');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513907366','2','São Domingos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513524122','1','Dois Vizinhos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509573508','1','Virmond');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512965260','1','Coronel Vivida');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508613565','1','Santiago');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510810961','1','Alfredo Wagner');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510508713','1','Tiradentes do Sul');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512554185','1','Ibirubá');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512474495','1','Salto do Lontra');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506754046','1','Realeza');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510380306','1','Ituporanga');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509935596','1','Roncador');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513284886','1','Floraí');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511777989','1','Alfredo Wagner');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511999517','1','Erval Seco');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512659106','1','Venâncio Aires');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512286685','1','Rio Branco do Ivaí');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511571169','1','Francisco Beltrão');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510089007','1','Três Palmeiras');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510949068','1','Chapada');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508769746','1','Nova Alvorada');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508772960','1','Presidente Nereu');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512395213','1','Tucunduva');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512747482','1','Nova Aurora');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512670922','1','Cerro Largo');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510949068','2','Chapada');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509189351','2','Flores da Cunha');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508322727','1','Jardim Alegre');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511576526','1','Novo Itacolomi');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508863950','1','Tapejara');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510692073','1','Mafra');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512618108','1','Carlos Gomes');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('507758594','1','Ijuí');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('507898230','1','Verê');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513579445','1','Paripiranga');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509830858','1','Três de Maio');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512643581','1','Panambi');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512729208','1','Nova Andradina');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512335392','1','Ubiretama');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('507882967','2','Japurá');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510495663','1','Eugênio de Castro');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512599510','1','Assis Chateaubriand');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509601753','1','Mercedes');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512026172','1','Maximiliano de Almeida');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512252911','1','Três Passos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511768420','1','Rio Branco do Ivaí');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513248222','1','Rio dos Índios');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512470060','1','Rondinha');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511378328','1','Assis Chateaubriand');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512518093','1','Marau');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508910843','1','Água Santa');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513011699','1','Godoy Moreira');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512823799','1','Nova Bassano');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512891196','1','São Jorge do Patrocínio');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509007520','1','São Lourenço do Sul');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508223429','1','Capanema');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508188784','1','Bela Vista da Caroba');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511379369','1','Arapuã');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512352391','1','Ibirapuitã');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512634304','1','Canguçu');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('9820725','1','Ibema');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512712204','1','Nova Ramada');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512495285','1','Senador Salgado Filho');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513533632','1','Janiópolis');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506865969','1','Prudentópolis');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512270462','1','Júlio de Castilhos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512780823','2','Santa Maria do Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510117551','1','São Pedro do Butiá');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510078851','1','Novo Xingu');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512677330','1','Protásio Alves');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511439948','1','Chopinzinho');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508641053','1','Ibirapuitã');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512300507','1','Tiradentes do Sul');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512522512','1','Chopinzinho');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512357618','1','Marechal Cândido Rondon');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511094550','1','Alpestre');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512355956','1','Frederico Westphalen');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('514301592','1','Ijuí');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510457178','1','São Paulo das Missões');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509629075','1','Dois Vizinhos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508291243','1','Guamiranga');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513990915','1','Carlos Gomes');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512441348','1','Capão do Cipó');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512651674','1','Senador Salgado Filho');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513130358','1','Imbuia');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('514245962','1','Verê');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510055012','1','Frederico Westphalen');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510060108','1','Capitão Leônidas Marques');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('507026112','1','Centralina');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509896770','1','Entre-Ijuís');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512601872','1','Vitória das Missões');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511287357','1','Três Barras do Paraná');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506212266','1','Toledo');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508916753','1','Alto Alegre');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511911774','1','Alfredo Wagner');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('514123551','1','Tuparendi');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513648453','1','Ampére');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('514563058','1','Três Barras do Paraná');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512482020','1','Soledade');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510602797','1','Erechim');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509228787','1','Frederico Westphalen');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513778439','1','Aurora');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511868281','1','Virmond');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512477755','1','Pouso Redondo');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508277787','1','Mato Rico');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513708609','1','Leoberto Leal');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511388861','1','Bom Sucesso do Sul');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513735136','1','Alpestre');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512301737','1','Jóia');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513980460','1','Espumoso');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512721361','1','Ipê');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512243415','1','Santa Izabel do Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512353491','1','Santo Augusto');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510564051','1','Entre Rios do Sul');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506629656','1','Saldanha Marinho');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511893735','1','Coronel Barros');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512358606','1','Missal');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512332483','1','Engenheiro Beltrão');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512244103','1','Charrua');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512946420','1','Barra do Guarita');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510745665','1','Três de Maio');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('507278364','1','Terra Roxa');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513386760','1','Vicente Dutra');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510632161','2','Rondinha');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512979738','1','Alecrim');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509059867','3','Ijuí');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508913472','2','Lagoa Vermelha');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508661403','1','Santo Ângelo');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512912002','1','Alegria');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512299563','1','Lapa');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510502139','1','Jaborá');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512301756','1','Passa Sete');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509042712','2','Muliterno');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512780823','1','Santa Maria do Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510344435','1','Augusto Pestana');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509668023','1','Céu Azul');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512873721','1','Assis Chateaubriand');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512436277','1','Catuípe');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512462892','1','Augusto Pestana');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513135023','1','Moreira Sales');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512388565','1','São João da Urtiga');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510946294','1','Dois Vizinhos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508591015','1','Chapada');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508992893','1','Santo Ângelo');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509445168','1','Canguçu');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508735553','1','Cacique Doble');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512652063','1','Enéas Marques');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510089493','1','Arroio do Tigre');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513258521','1','Imbuia');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513750066','1','Poço Verde');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509905957','1','São Jorge d'Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512380960','1','Concórdia');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509149957','1','Vitória das Missões');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511126122','1','Santa Tereza do Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509268185','1','Tangará');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510726863','1','Entre-Ijuís');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513597971','1','Tobias Barreto');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513610367','1','Aratiba');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512634363','1','Santa Terezinha de Itaipu');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512580489','1','Salvador das Missões');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513773093','1','Farroupilha');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512687164','1','Espumoso');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512559580','1','Goioerê');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512788714','1','Vicente Dutra');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('507758594','3','Catuípe');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509353671','1','Arroio do Tigre');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512097666','1','Leoberto Leal');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508195634','1','Nova Aurora');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508673246','1','Santo Ângelo');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511578700','1','Tiradentes do Sul');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509511188','1','São Jorge d'Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('9997201','1','Palmeira das Missões');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512387070','1','Boa Vista do Incra');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511738404','1','Leoberto Leal');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('514268609','1','Cruzaltense');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511291090','1','Constantina');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('507264950','1','Verê');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512233215','1','Palmitinho');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511051688','1','Palmitinho');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512660091','1','Não-Me-Toque');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509056841','1','Imbuia');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511492941','1','Planalto');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513907366','1','Coronel Martins');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508788950','1','Cerro Negro');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508769988','1','Ubiretama');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510210451','1','Gararu');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508668341','1','Palmeira das Missões');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512251294','1','Novo Tiradentes');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509802861','1','Porto Mauá');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512319700','1','Ituporanga');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511621705','1','Capanema');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512450168','1','Centenário');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509080945','2','Faxinal do Soturno');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513750705','1','Salgado Filho');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511338034','1','Vera Cruz do Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513874725','1','Saudade do Iguaçu');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506401582','1','Pinhão');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512531126','1','Cândido Godói');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509880976','1','Alfredo Wagner');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513445681','1','Redentora');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511805593','1','Sítio do Quinto');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513942583','1','Cerro Grande');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508774903','1','Rolador');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510346204','1','Dionísio Cerqueira');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506606078','1','Sítio do Quinto');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512407235','2','Constantina');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510528460','1','Independência');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508851064','1','Frederico Westphalen');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513533685','1','Sulina');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512576539','1','Três de Maio');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512510427','1','Ajuricaba');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506860124','1','Três Passos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508232904','1','Maximiliano de Almeida');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506942245','1','São Jorge d'Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510406036','1','Tangará');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511054643','1','Rio Azul');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512280094','1','Nova Prata');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508274464','1','Irati');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510495682','1','Iretama');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509380505','1','Pérola d'Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506290616','1','Dourados');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513561341','1','Euclides da Cunha');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508819744','1','Montauri');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512903337','1','Caibi');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('507375125','1','São João');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512601417','1','Gaurama');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512258400','1','Carlos Gomes');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512248671','1','Entre-Ijuís');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513614157','1','Sarandi');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510474148','1','Vicente Dutra');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508383644','1','Boa Esperança do Iguaçu');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512657554','1','Mondaí');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509715213','1','Quedas do Iguaçu');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512521568','1','Barão de Cotegipe');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508739608','3','São Miguel das Missões');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511518229','1','Petrolândia');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512387478','1','Segredo');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511712083','1','Cruzaltense');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511217270','1','Coronel Vivida');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512448454','1','Trombudo Central');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512651674','2','Senador Salgado Filho');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513957637','1','Pérola d'Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512737324','1','Augusto Pestana');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('507416561','1','Agrolândia');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510124977','1','Vera Cruz do Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512688647','1','Urupema');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508434395','1','Nova Aurora');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('514347760','1','Cunha Porã');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506916303','1','Ibirapuitã');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512741570','1','Planalto');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512666278','2','Giruá');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512609430','1','Humaitá');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512468602','1','Alto Bela Vista');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513716338','1','Jupiá');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512482466','1','Fontoura Xavier');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512632655','1','Santa Rosa');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508796197','1','Cruz Alta');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510431667','1','Herval d'Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511272221','1','Pérola d'Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509993672','1','Nova Prata do Iguaçu');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512366989','1','Vicente Dutra');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512434468','2','Mato Queimado');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511489052','1','Três Barras do Paraná');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('507256668','1','Iporã do Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513848486','1','Dois Vizinhos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512724190','1','Braço do Trombudo');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512742935','1','Salvador das Missões');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511125277','1','Toledo');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512651104','1','Fortaleza dos Valos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508335930','1','Aurora');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512578739','1','Caseiros');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('514608606','1','Angelina');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512620766','1','São Francisco de Assis');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513750926','1','Cruzeiro do Iguaçu');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510680842','1','São Joaquim');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513680109','1','Liberato Salzano');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511613692','1','São João da Urtiga');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511532957','1','Chopinzinho');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508887000','1','Passa Sete');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512549211','1','Cruz Machado');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512502984','1','Salto do Lontra');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509865198','1','Novo Tiradentes');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('514424897','1','Independência');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513271691','1','Santa Helena');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513874010','1','Sulina');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('514251016','1','Alpestre');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506697447','1','Nossa Senhora Aparecida');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512061679','1','Novo Horizonte');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512396965','1','Lagoa Vermelha');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512266697','1','Santa Bárbara do Sul');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513418603','1','Dois Vizinhos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513795496','2','Manoel Ribas');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511917450','1','Marmeleiro');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508920137','2','Sertão');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510622964','1','Alpestre');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('514379770','1','Novo Machado');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('511524986','1','Santa Tereza do Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513750636','1','Enéas Marques');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506717504','1','Espumoso');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508961802','1','Barão do Triunfo');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('508126527','1','Giruá');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510576800','1','Paim Filho');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509275975','1','Venâncio Aires');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512243214','1','Porto Lucena');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('510548881','1','Celso Ramos');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513192386','1','Santa Izabel do Oeste');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513096346','1','Frederico Westphalen');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('512323997','1','Quilombo');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('506397085','1','Santa Cecília do Sul');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('513349572','1','Rodeio Bonito');
INSERT INTO PUBLIC.municipio_glebas(ref_bacen, nu_ordem, nome) VALUES ('509055785','2','Lagoa Vermelha');
