INSERT INTO PUBLIC.GRAO (IDGRAO, DESCRICAO) VALUES (0, 'N�o se aplica');
INSERT INTO PUBLIC.GRAO (IDGRAO, DESCRICAO) VALUES (3, 'Semente');
INSERT INTO PUBLIC.GRAO (IDGRAO, DESCRICAO) VALUES (8, 'Gr�o/Consumo');
