INSERT INTO PUBLIC.SOLO (IDSOLO, DESCRICAO) VALUES (1, 'Solo arenoso');
INSERT INTO PUBLIC.SOLO (IDSOLO, DESCRICAO) VALUES (2, 'Solo com textura m�dia');
INSERT INTO PUBLIC.SOLO (IDSOLO, DESCRICAO) VALUES (3, 'Solo argiloso');
INSERT INTO PUBLIC.SOLO (IDSOLO, DESCRICAO) VALUES (9, 'Tipo de solo desconhecido');
